######## Register
POST https://coursani.herokuapp.com/api/auth/register
Content-Type: application/json

{
    "username": "PhamHai",
    "password": "123456"
}

################################ Login
POST https://coursani.herokuapp.com/api/auth/login
Content-Type: application/json

{
    "username": "PhamHai",
    "password": "123456"
}

######## post Create new course
POST https://coursani.herokuapp.com/api/course/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

{
    "title": "Học nodeJS ",
    "description": "Học NodeJS và Express",
    "url": "https://expressjs.com/"
}
######## get list course 
GET https://coursani.herokuapp.com/api/course/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

######## put edit course
PUT https://coursani.herokuapp.com/api/course/61346f709991ee0004bfa48e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

{
    "title": "Hoc NodeJS",
    "description": "Học NodeJS và Express và nhiều thứ linh tinh",
    "url": "https://expressjs.com/",
    "state": "DOING"
}
######## put 
DELETE http://localhost:5000/api/course/6119cdd1a7682b1e4c2677c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE5YmQ3NWJhYWY4ZDJmYWNhYWQwYjciLCJpYXQiOjE2MjkwNzY4ODl9.yXsC34bcL0t0RCNpxFnCctnA83t1xOSmYJfcyuV6_wk
